/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        mainColor: "#28CB8B",
        secondaryColor: "#263238",
        info: "#2194f3",
        black: "#263238",
        darkGrey: "#4D4D4D",
        grey: "#717171",
        greyBlue: "#ABBED1",
        silver: "#F5F7FA",
        white: "#FFFFFF",
        lightGrey: "#89939E",
        mainColorShadeOne: "#43A046",
        mainColorShadeTwo: "#388E3B",
        mainColorShadeThree: "#237D31",
        mainColorShadeFour: "#1B5E1F",
        mainColorShadeFive: "#103E13",
        mainColorTintOne: "#66BB69",
        mainColorTintTwo: "#81C784",
        mainColorTintThree: "#A5D6A7",
        mainColorTintFour: "#C8E6C9",
        mainColorTintFive: "#E8F5E9",
        warning: "#FBC02D",
        error: "#E53835",
        success: "#2E7D31",
      },
      fontFamily: {
        sans: ["Outfit", "sans-serif"],
      },
      fontSize: {
        "1xl": "10px",
        "2xl": "14px",
        "3xl": "16px",
        "4xl": "20px",
        "5xl": "24px",
        "6xl": "26px",
        "7xl": "32px",
        "8xl": "34px",
        "9xl": "36px",
        "10xl": "42px",
        "11xl": "44px",
        "12xl": "46px",
      },
      screens: {
        xsm: "320px",
        sm: "480px",
        xmd: "640px",
        md: "768px",
        xlg: "1024px",
        lg: "1280px",
      },
    },
  },
  plugins: ["@tailwindcss/line-clamp"],
};
